# Import Libraries

In [5]:
import pandas as pd

# Read raw data

In [6]:
usda_df = pd.read_csv('../../raw_data/comprehensive_foods_usda.csv')
healthyFoods_df= pd.read_csv('../../raw_data/healthy_foods_database.csv')
allergens_df = pd.read_csv("../../raw_data/foods_health_scores_allergens.csv", encoding="utf-8")

# Exploration

In [7]:
print(f"{'Dataset':<15} {'Rows':>8} {'Cols':>6}")
print("-" * 32)
print(f"{'USDA':<15} {usda_df.shape[0]:>8,} {usda_df.shape[1]:>6}")
print(f"{'HealthyFoods':<15} {healthyFoods_df.shape[0]:>8,} {healthyFoods_df.shape[1]:>6}")
print(f"{'Allergens':<15} {allergens_df.shape[0]:>8,} {allergens_df.shape[1]:>6}")

Dataset             Rows   Cols
--------------------------------
USDA              40,000     24
HealthyFoods       9,028     10
Allergens          4,997     24

In [8]:
print("-"*80)
print(" DATASET 1: USDA FOODS (Main Dataset)")
print("-"*80)
print(f"\nShape: {usda_df.shape}")
print(f"\nColumn Names:\n{usda_df.columns.tolist()}")
print(f"\nFirst 3 rows:")
display(usda_df.head(3))

print("\n" + "-"*80)
print(" DATASET 2: HEALTHY FOODS")
print("-"*80)
print(f"\nShape: {healthyFoods_df.shape}")
print(f"\nColumn Names:\n{healthyFoods_df.columns.tolist()}")
print(f"\nFirst 3 rows:")
display(healthyFoods_df.head(3))

print("\n" + "-"*80)
print(" DATASET 3: ALLERGENS FOCUSED")
print("-"*80)
print(f"\nShape: {allergens_df.shape}")
print(f"\nColumn Names:\n{allergens_df.columns.tolist()}")
display(allergens_df.head(3))

print("\n" + "-"*80)
print(" DATASET 3: ALLERGENS")
print("-"*80)
print(f"\nShape: {allergens_df.shape}")
print(f"\nColumn Names:\n{allergens_df.columns.tolist()}")
display(allergens_df.head(3))

--------------------------------------------------------------------------------
 DATASET 1: USDA FOODS (Main Dataset)
--------------------------------------------------------------------------------

Shape: (40000, 24)

Column Names:
['fdc_id', 'food_name', 'data_type', 'food_category', 'brand_owner', 'brand_name', 'ingredients', 'serving_size', 'serving_unit', 'household_serving', 'calories', 'carbs_g', 'calcium_mg', 'fat_g', 'protein_g', 'saturated_fat_g', 'vitamin_c_mg', 'fiber_g', 'iron_mg', 'sodium_mg', 'sugar_g', 'cholesterol_mg', 'health_score', 'food_type']

First 3 rows:

,fdc_id,food_name,data_type,food_category,brand_owner,brand_name,ingredients,serving_size,serving_unit,household_serving,...,protein_g,saturated_fat_g,vitamin_c_mg,fiber_g,iron_mg,sodium_mg,sugar_g,cholesterol_mg,health_score,food_type
0,167782,"Abiyuch, raw",SR Legacy,Fruits and Fruit Juices,NaN,NaN,NaN,NaN,NaN,NaN,...,1.5,0.014,54.1,5.3,1.61,20.0,8.55,NaN,65,Fruits
1,171687,"Acerola juice, raw",SR Legacy,Fruits and Fruit Juices,NaN,NaN,NaN,NaN,NaN,NaN,...,0.4,0.068,1600.0,0.3,0.50,3.0,4.50,0.0,55,Fruits
2,171686,"Acerola, (west indian cherry), raw",SR Legacy,Fruits and Fruit Juices,NaN,NaN,NaN,NaN,NaN,NaN,...,0.4,0.068,1680.0,1.1,0.20,7.0,NaN,0.0,55,Fruits

--------------------------------------------------------------------------------
 DATASET 2: HEALTHY FOODS
--------------------------------------------------------------------------------

Shape: (9028, 10)

Column Names:
['food_name', 'food_type', 'calories', 'protein_g', 'fat_g', 'carbs_g', 'fiber_g', 'sugar_g', 'sodium_mg', 'health_score']

First 3 rows:

,food_name,food_type,calories,protein_g,fat_g,carbs_g,fiber_g,sugar_g,sodium_mg,health_score
0,"Abiyuch, raw",Fruits,69.0,1.50,0.10,17.6,5.30,8.55,20.000,65
1,"Agave, raw (Southwest)",Other,68.0,0.52,0.15,16.2,6.60,2.58,14.000,60
2,"Almond butter, creamy",Other,603.0,20.80,53.00,21.2,9.72,NaN,0.996,70

--------------------------------------------------------------------------------
 DATASET 3: ALLERGENS FOCUSED
--------------------------------------------------------------------------------

Shape: (4997, 24)

Column Names:
['product_name', 'brands', 'categories', 'ingredients', 'nutriscore_grade', 'nova_group', 'ecoscore_grade', 'allergens', 'energy_kcal', 'fat_100g', 'saturated_fat_100g', 'carbs_100g', 'sugars_100g', 'fiber_100g', 'proteins_100g', 'salt_100g', 'sodium_100g', 'contains_gluten', 'contains_dairy', 'contains_nuts', 'contains_soy', 'contains_eggs', 'contains_fish', 'food_type']

,product_name,brands,categories,ingredients,nutriscore_grade,nova_group,ecoscore_grade,allergens,energy_kcal,fat_100g,...,proteins_100g,salt_100g,sodium_100g,contains_gluten,contains_dairy,contains_nuts,contains_soy,contains_eggs,contains_fish,food_type
0,Sidi Ali,سيدي علي,"en:beverages-and-beverages-preparations, en:be...",OBD1 999 999 1112606 266963207 mb,A,NaN,NOT-APPLICABLE,NaN,0.0,0.0,...,0.0,0.000,0.000,False,False,False,False,False,False,Branded/Packaged
1,Perly,Perly,"en:dairies, en:fermented-foods, en:fermented-m...","milk cream, cream, sugar, banana, bacteria",UNKNOWN,3.0,B,"en:banana, en:milk",97.0,3.0,...,8.0,NaN,NaN,False,True,False,False,False,False,Branded/Packaged
2,Sidi Ali,Sidi Ali,"en:beverages-and-beverages-preparations, en:be...","Sodium, Calcium, Magnésium, Potassium, Bicarbo...",A,1.0,NOT-APPLICABLE,NaN,NaN,NaN,...,NaN,0.065,0.026,False,False,False,False,False,False,Branded/Packaged

--------------------------------------------------------------------------------
 DATASET 3: ALLERGENS
--------------------------------------------------------------------------------

Shape: (4997, 24)

Column Names:
['product_name', 'brands', 'categories', 'ingredients', 'nutriscore_grade', 'nova_group', 'ecoscore_grade', 'allergens', 'energy_kcal', 'fat_100g', 'saturated_fat_100g', 'carbs_100g', 'sugars_100g', 'fiber_100g', 'proteins_100g', 'salt_100g', 'sodium_100g', 'contains_gluten', 'contains_dairy', 'contains_nuts', 'contains_soy', 'contains_eggs', 'contains_fish', 'food_type']

,product_name,brands,categories,ingredients,nutriscore_grade,nova_group,ecoscore_grade,allergens,energy_kcal,fat_100g,...,proteins_100g,salt_100g,sodium_100g,contains_gluten,contains_dairy,contains_nuts,contains_soy,contains_eggs,contains_fish,food_type
0,Sidi Ali,سيدي علي,"en:beverages-and-beverages-preparations, en:be...",OBD1 999 999 1112606 266963207 mb,A,NaN,NOT-APPLICABLE,NaN,0.0,0.0,...,0.0,0.000,0.000,False,False,False,False,False,False,Branded/Packaged
1,Perly,Perly,"en:dairies, en:fermented-foods, en:fermented-m...","milk cream, cream, sugar, banana, bacteria",UNKNOWN,3.0,B,"en:banana, en:milk",97.0,3.0,...,8.0,NaN,NaN,False,True,False,False,False,False,Branded/Packaged
2,Sidi Ali,Sidi Ali,"en:beverages-and-beverages-preparations, en:be...","Sodium, Calcium, Magnésium, Potassium, Bicarbo...",A,1.0,NOT-APPLICABLE,NaN,NaN,NaN,...,NaN,0.065,0.026,False,False,False,False,False,False,Branded/Packaged

# Save to bronze_layer (as-is)

In [9]:
usda_df.to_csv("../data/bronze_layer/usda.csv", index=False)
healthyFoods_df.to_csv("../data/bronze_layer/healthyFoods.csv", index=False)
allergens_df.to_csv("../data/bronze_layer/allergens.csv", index=False)